USE [master]
GO

/****** Object:  Database [BankingDatabaseSystem]    Script Date: 4/19/2022 2:17:36 AM ******/
CREATE DATABASE [BankingDatabaseSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankingDatabaseSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BankingDatabaseSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BankingDatabaseSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BankingDatabaseSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankingDatabaseSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BankingDatabaseSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BankingDatabaseSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BankingDatabaseSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BankingDatabaseSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BankingDatabaseSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [BankingDatabaseSystem] SET  MULTI_USER 
GO

ALTER DATABASE [BankingDatabaseSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BankingDatabaseSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BankingDatabaseSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BankingDatabaseSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BankingDatabaseSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BankingDatabaseSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BankingDatabaseSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BankingDatabaseSystem] SET  READ_WRITE 
GO


